# Generated by Django 3.1.8 on 2021-04-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg_app', '0002_auto_20210420_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
